apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: dapp
  name: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-ethereum-default: "true"
        io.kompose.service: dapp
    spec:
      containers:
        - image: aratrika1996/docker-eth-backend:4.2.0
          name: dapp
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
      restartPolicy: Always
