apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-eth-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-eth-server
  template:
    metadata:
      labels:
        app: docker-eth-server
    spec:
      containers:
        - name: backend
          image: aratrika1996/docker-eth-server:latest
          resources:
            limits:
              cpu: "250m" # 250 millicores
              memory: "500Mi"
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
