apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: cluster-role
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources:
      [
        "pods",
        "services",
        "deployments",
        "replicasets",
        "statefulsets",
        "secrets",
        "persistentvolumeclaims",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]