apiVersion: v1
kind: Service
metadata:
  name: docker-eth-server
spec:
  type: LoadBalancer
  selector:
    app: docker-eth-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
