version: "3"
services:
  docker-eth-ganache-service:
    image: aratrika1996/docker-eth-ganache:latest
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  docker-eth-server-service:
    image: aratrika1996/docker-eth-server:latest
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - docker-eth-ganache-service

  docker-eth-service:
    image: aratrika1996/docker-eth-frontend:latest
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - docker-eth-server-service
